# Generated by Django 4.1.7 on 2023-02-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_girl_avatar.png', upload_to='avatars/%y/%m/%d'),
        ),
    ]
