# Generated by Django 4.1.7 on 2023-02-26 20:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/media/avatars/default_avatar.jpeg', upload_to=users.models.get_image_path),
        ),
    ]
